name: IOT DEVICE ANDROID RELEASE CI

on:
  push:
    tags:
      - '*'

env:
  IOT_SONATYPE_USERNAME: ${{ secrets.IOT_SONATYPE_USERNAME }}
  IOT_SONATYPE_PASSWORD: ${{ secrets.IOT_SONATYPE_PASSWORD }}
  GPG_DECRYPT_PASSPHRASE: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          rm -rf hub-device-android/app-config.json
          gpg -d --passphrase "$GPG_DECRYPT_PASSPHRASE" --batch --quiet .github/hub-device-android/app-config.json.asc > hub-device-android/app-config.json
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Adapt build.gradle from debug to release
        run: |
          sed -i 's#iot_explorer-debug#iot_explorer-release#g' explorer-device-android/iot_explorer/build.gradle
          sed -i 's#-SNAPSHOT##g' explorer-device-android/iot_explorer/build.gradle
          sed -i 's#iot_core-debug#iot_core-release#g' hub-device-android/iot_core/build.gradle
          sed -i 's#-SNAPSHOT##g' hub-device-android/iot_core/build.gradle
          sed -i 's#iot_service-debug#iot_service-release#g' hub-device-android/iot_service/build.gradle
          sed -i 's#-SNAPSHOT##g' hub-device-android/iot_service/build.gradle
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish aar and jar to Maven
        run: ./gradlew publish
      - name: Archive the apks
        uses: actions/upload-artifact@v2
        with:
          path: '*-device-android/*-demo/build/outputs/apk/release/*.apk'
      - name: Upload apks to PGY
        env:
          IOT_PGYER_API_KEY: ${{ secrets.IOT_PGYER_API_KEY }}
        run: |
          apk=$(ls explorer-device-android/explorer-demo/build/outputs/apk/release/*.apk)
          curl -F "file=@${apk}" -F "_api_key=$IOT_PGYER_API_KEY" https://www.pgyer.com/apiv2/app/upload
          apk=$(ls hub-device-android/hub-demo/build/outputs/apk/release/*.apk)
          curl -F "file=@${apk}" -F "_api_key=$IOT_PGYER_API_KEY" https://www.pgyer.com/apiv2/app/upload
